dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qos-port: 33333
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: 127.0.0.1:2181
    #指定注册中心协议
    protocol: zookeeper
