sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 9.tcp.cpolar.top
    port: 13977
    database: reggie
    username: root
    password: 123456
  redis:
    host: 12.tcp.cpolar.top
    port: 13224
    database: 0
  wechat:
    appid: wx1ff313bc761d8d7b
    secret: 4678a6487c516d311e10ac1856fbd7e6
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php